### ISSUE TITLE
website deisgn guideline

### ISSUE THREAD

**Issue by mark19891107** [PDIS/web#23]
制定網頁設計規範
大致上包含

- 色彩規範
- 文字排列
- 基本使用者介面
  - 按鈕
  - 分頁
  - 輸入筐
- 文章列表

**Comment by jokeum** [comment]
- 色彩規範
1. link: #4B0056
2. active link & highlight text: #D66FE5
3. text: #111
- 文字排列
1. title: h1~h6 bold Noto-serif
2. desc: h1~h6 italic Noto-serif
3. text: p Noto-serif
4. button & tag: Franklin Gothic Condensed
5. slogan: Rockwell Condensed
- 基本使用者介面
  - 按鈕
  1. external link
  - 分頁
  1. lazy-loading
  - 輸入筐
  1. #888 solid 1px
- 文章列表
1. 2-column timeline with categories and tags
