### ISSUE TITLE
Refresh 之後會出現 github pages 的 404

### ISSUE THREAD

**Issue by yurenju** [PDIS/web#27]
### STR:
1. click `What we do`
    ![image](https://cloud.githubusercontent.com/assets/22155/21260942/76b894a4-c3c3-11e6-997d-8c6837f3c4ca.png)
2. refresh page

### expected:
頁面重整，畫面上緣捲到 `what we do`

### actually:
出現 github pages 404

### note:
應該是用了 HTML5 routing 的關係，重導之後沒有 hashtag 所以會出現 404，可能還是前面要放一台可以處理 routing 的 node.js server。

**Comment by mark19891107** [comment]
已改用有 Hashtag 版的URL囉 感謝通知
