### ISSUE TITLE
首頁未記住語言偏好前是英文，語言選單不明顯

### ISSUE THREAD

**Issue by bestian** [PDIS/web#31]
![pdis_ _public_digital_innovation_space](https://cloud.githubusercontent.com/assets/109048/22319176/661b9bb0-e3bb-11e6-88d0-0b6664f71469.jpg)

window.navigator.language 觸發是好方法，
不過不一定所有所有中文用戶的navigator.language都是zh_TW等中文

所以同步把語言選單弄醒目一點，例如壓個底色、字放大and/or往上移一些，還是會更好 :)

**Comment by jokeum** [comment]
that's right. gonna highlight it a little bit.
