### ISSUE TITLE
stuck on redirect notice page

### ISSUE THREAD

**Issue by shuyanglin** [PDIS/web#36]
https://www.google.com/url?rct=j&amp;sa=t&amp;url=http://www.civilmedia.tw/archives/61409&amp;ct=ga&amp;cd=CAIyIGIxYmVjMjExZTFhYTJlYTI6Y29tLnR3OnpoLVRXOlRX&amp;usg=AFQjCNF-W8ucdravWKz8nzNVJtyv6a3J_w

**Comment by jokeum** [comment]
the link above is not working?

**Comment by mark19891107** [comment]
replace amp;
rss2json.com add some "amp;" to link
