### ISSUE TITLE
網站內容新增至 talk.pdis.tw

### ISSUE THREAD

**Issue by mark19891107** [PDIS/web#4]
麻煩 @shuyanglin 提供mockup上的markdown
再麻煩 @targee 規劃怎麼放進talk.pdis.tw中

**Comment by shuyanglin** [comment]
好喔，內容基本上都會放這ㄦ
https://ey.sandcats.io/grain/j5eZWzhfZcc27oFehoLyKS/files/PDIS/pdis%20website/website%20content.md

**Comment by shuyanglin** [comment]
both open api and civic participation are up

**Comment by targee** [comment]
talk.pdis.tw目前使用pdis-site下的子類別的post當作資料儲存的地方
初步規劃：
what-we-do-open-api、what-we-do-civic-participation的第一篇放summary第二篇放detail
how-we-work-tools的每篇放說明+小圖
how-we-work-track-pdis則是還不確定做法可以再討論看看~
