### ISSUE TITLE
blank image/text when embedded

### ISSUE THREAD

**Issue by shuyanglin** [PDIS/web#7]
https://www.dropbox.com/s/eevxmpb4ntgdreo/Screenshot%202016-11-19%2015.45.31.png?dl=0

**Comment by mark19891107** [comment]
<img width="492" alt="2016-11-21 4 03 29" src="https://cloud.githubusercontent.com/assets/7321879/20474948/1c4b75c2-b004-11e6-8a3a-5d1c1d441641.png">

@audreyt 已修正囉＠＠
